# Execute this from terminal or powershell
# You must place this file in a directory 
# and change your working directory to that directory
# Call: docker compose -f .\dc-mssql.yml up -d

services:
  mssqlServer:
    container_name: portableTestDB
    #image: mcr.microsoft.com/mssql/server:2019-GDR1-ubuntu-16.04
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - "1433:1433"
      # - "135:135"
      # - "51000:51000"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password!"
      MSSQL_RPC_PORT: "135"
      MSSQL_DTC_TCP_PORT: "51000"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
